# Built-in config:
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml

# We do not typically use/need class documentation
Documentation:
    Enabled: false

Metrics/LineLength:
    Max: 120

Metrics/MethodLength:
  Max: 15

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/RaiseArgs:
  Enabled: false

Metrics/ParameterLists:
  Max: 6

Style/SignalException:
  EnforcedStyle: only_raise

Style/MultilineArrayBraceLayout:
  Enabled: false

Style/MultilineHashBraceLayout:
  Enabled: false

Style/MultilineMethodCallBraceLayout:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Style/Semicolon:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false
# Run rails specific checks
# https://github.com/bbatsov/rubocop#rails
Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.3
  Include:
    # Include important files that don't end in .rb
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    # exclude files in /vendor because some CI systems put gems in here e.g.
    # TravisCI
    - 'vendor/**/*'
    # exclude the autogenerated schema file as we don't have any control over
    # its format
    - 'db/schema.rb'
    - 'bin/**/*'
    - 'doc/**/*'
    - 'db/migrate/**/*'
    - 'db/seeds.rb'
    - 'features/**/*.rb'
    - 'config/initializers/devise.rb'
    - 'ember-frontend/**/*'